### ISSUE TITLE
How to extract the texture ?

### ISSUE THREAD

**Issue by naufalso** [idrl-lab/Full-coverage-camouflage-adversarial-attack#2]
Hello, thanks for the great work.
I am wondering how we can extract the generated attack texture to use it on other 3D software or print it for the real world?
Is it possible for us to save the texture as an image file?
Because we found that the output texture is saved as a NumPy file, which can only be used for this neural renderer code.

Thank you.

**Comment by winterwindwang** [comment]
As far as I know, it is impossible to save the texture as an image file with neural renderer.
